fastlane_version "2.48.0"

opt_out_crash_reporting

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :alpha do
    gradle(task: "assembleRelease")
    supply
  end
end

