fastlane_version "2.49.0"

opt_out_crash_reporting

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Validate a new version to Google Play - Alpha channel"
  lane :alpha do
    gradle(
        task: 'assembleRelease'
    )
    supply(
        track: 'alpha',
        skip_upload_screenshots: true,
        validate_only: true
    )
  end

  desc "Deploy a new version to Google Play - Alpha channel"
  lane :alphadeploy do
    gradle(
        task: 'assembleRelease'
    )
    supply(
        track: 'alpha',
        skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to Google Play - Alpha channel + screenshots"
  lane :alphadeployscreenshots do
    gradle(
        task: 'assembleRelease'
    )
    supply(
        track: 'alpha',
    )
  end
end

